name: build_docker

on:
  release:
    types: [created]  # 仅在创建新的发布时触发
  workflow_dispatch:   # 支持手动触发
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., v1.0.0)'
        required: true
        default: 'latest'
      push_to_acr:
        description: 'Push to Alibaba Cloud ACR?'
        type: boolean
        required: true
        default: true

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud Container Registry (ACR)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.push_to_acr == true || github.event_name == 'release' }}
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_ACR_USERNAME }}
          password: ${{ secrets.ALIYUN_ACR_PASSWORD }}

      - name: Set up environment variables
        run: |
          REPOSITORY_NAME_PART=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)
          BUILD_TAG=$(date +'%y%m%d%H%M')
          echo "REPOSITORY_NAME_PART=$REPOSITORY_NAME_PART" >> $GITHUB_ENV
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPOSITORY_NAME_PART: $REPOSITORY_NAME_PART"
          echo "BUILD_TAG: $BUILD_TAG"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.event_name == 'workflow_dispatch' && inputs.push_to_acr == true || github.event_name == 'release' }}
          platforms: linux/amd64
          tags: |
            registry.cn-hangzhou.aliyuncs.com/starfishes/nb2_docker:${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || github.event.release.tag_name }}
            registry.cn-hangzhou.aliyuncs.com/starfishes/nb2_docker:latest